### ISSUE TITLE
Asynchronous GSheets and R6Stats

### ISSUE THREAD

**Issue by Tobotimus** [Tobotimus/Tobo-Cogs#1]
Yeah, this is gonna be something to redo after exams. And I feel like I just rewrote all of gsheets >:( 

Basically gonna have to make the cog independent of `google-api-python-client` and `oauth2client` requests.

**Comment by Kabboose** [comment]
What's the issue this raises? Are Gsheets and R6Stats interfering with each other?

**Comment by Tobotimus** [comment]
No, simply the fact that both cogs are making requests using non-threadsafe libraries
