### ISSUE TITLE
[Suggestion] More than one channel for Welcomecount

### ISSUE THREAD

**Issue by Lionirdeadman** [Tobotimus/Tobo-Cogs#2]
Ability to set more than one channel for welcome message, I have 2 general chats because it's a bilingual server and so I want to have the welcome message on both channel.

**Comment by Tobotimus** [comment]
@Lionirdeadman Pretty good suggestion. I planned on implementing this during development of the cog, but held back because it required me to redesign how the settings are stored, but it's not a difficult change. I'll get to work :smiley:
