### ISSUE TITLE
[V3 Strikes] Add command for listing strikes for multiple members

### ISSUE THREAD

**Issue by Tobotimus** [Tobotimus/Tobo-Cogs#22]
Proposed name of command: `serverstrikes`

# Subcommands
Defaults to `all` when the subcommand is omitted.

- `all` Displays a table of all individual strikes from the past X days, default X=30, formatted as following:
    ```
    User      | Time + Date (UTC) | Moderator      | Strike ID          | Reason
    --------- | ----------------- | -------------- | ------------------ | ------
    User#1234 | hh:MM AP dd-mm-yy | Tobotimus#1234 | 123456789012345678 | reason
    ```
- `count`: Displays a table showing the total strike count for each member from the past X days, from a selection of Y members, sorted by Z, default X=30, Y=100, Z=latest, formatted as following:
    ```
    User      | Strike Count | Latest Strike Given (UTC)
    --------- | ------------ | -------------------------
    User#1234 | 1            | hh:MM AP dd-mm-yy
    ```

# Data
The info as it's currently stored is sufficient to extract this information, however it would be pretty inefficient. Here's a proposed alternative:

```py
# old

"MEMBERS": {
    MEMBERID: {
        "strikes": [
            {
                "timestamp"" ...,
                "reason": ...,
                "moderator": ...,
                "id": STRIKEID
            },
            ...
        ]
    },
    ...
}

# new

"MEMBERS": {
    MEMBERID: {
        "strikes": [
            STRIKEID,
            ...
        ]
    },
    ...
},
"STRIKES": {
    STRIKEID: {
            "reason": ...,
            "moderator": ...
    },
    ...
}
```

We can get rid of the "timestamp" too, since it can be extracted from the strike id using `discord.utils.snowflake_time()`.

These changes to the data don't have to be breaking - we can use a safeguard to migrate data on cog load to the new format for 2 weeks following implementation.

**Comment by ghost** [comment]
I really like this idea. Is this being worked on at all? My server would really benefit from it.

**Comment by Tobotimus** [comment]
@SevereMatrex Unfortunately not! I'm a bit busy with the core bot at the moment, but to be honest I had forgotten about this issue. Perhaps I could spend some time on it today :)

**Comment by ghost** [comment]
That'd be great! Lemme know if you need any help.

**Comment by Tobotimus** [comment]
@SevereMatrex Thanks for the offer. I've taken a look at strikes this morning and I've rediscovered lots of things I want to do with this cog. Get keen for some new features soon! :grin:

**Comment by Tobotimus** [comment]
@SevereMatrex All done! Give it a try :smile:

Note: I decided not to do exactly as this issue has described - the two new commands are [P]allstrikes and [P]strikecounts. Also the data definition is totally different to how I described, although this is probably of less interest to you :D

**Comment by ghost** [comment]
There seems to be an error. I can't load the cog anymore. I won't be able
to check my console for a while, but I thought I would let you know.

**Comment by Tobotimus** [comment]
@SevereMatrex You can check the latest error with `[P]traceback` or my errorlogs cog, and the error will tell you how to fix it. Sorry it's a little unintuitive, but it's kind of a bug with downloader.

Anyway, the fix is to do `[P]pipinstall tabulate[widechars]` in discord :)
