### ISSUE TITLE
Discord Member Stream Alert/s 

### ISSUE THREAD

**Issue by Sashasonic** [Tobotimus/Tobo-Cogs#47]
Hi there, 

As mentioned in your cog-support channel, am posting the reminder as asked.  _I too won't leave it too long as may forget._ 

To post auto Twitch Stream alerts of Members, **very similar to** a 'new youtube upload' via the rss cog, would be awesome as it would also 'publish' a preview video style(?) _'playable' as such.._

![rss youtube preview](https://user-images.githubusercontent.com/22435568/58743313-475e2080-8472-11e9-91dc-8d642e3ccb43.JPG)

I find to add popular streamers is one thing.. but to go through and manually add people, who come and go.. (especially as the channel I used to use is named 'Members Gallery') & simply may not stay around, is superfluous and thereby don't usually bother, (I usually just give an unhoisted role of a different color atm) also even in a small server of 200/300 it would be far too laborious. Therefore to have a cog to 'auto' announce with various settings, ie: requiring a prior role/or not, would be great.

It's one of the main reasons I kept the "Now Live" bot around, but now it's going through all sorts of changes, including online management only :( would be great to not need it anymore, and is taking ages to be upgraded etc..

TIA
_Sasha_

_nb: posted as requested as a reminder for @Tobotimus_

**Comment by Tobotimus** [comment]
Hey mate. So I'm starting to work on this, and just a few notes:
- ~~I don't believe it's possible to have a *video* preview with a twitch stream, only a thumbnail.YouTube gets special treatment in the Discord client.~~ *(Edit: You actually can get a video preview with twitch)*. So I'll probably make it look somewhat similar to the streamalerts posted by the streams cog.
- I think I want to keep it simple and just have a single channel in each guild that can be set as the alerts channel. Anyone who receives the role gets an alert posted, anyone who has to role removed gets their alert removed.

Does that sound alright?

**Comment by Tobotimus** [comment]
I actually decided to go with the YouTube RSS design, as you suggested, like the following:
![image](https://user-images.githubusercontent.com/7438501/60958523-d6036e80-a349-11e9-9da6-a8594fb450ec.png)

Alerts are still removed once the streamrole is removed.

**Comment by Sashasonic** [comment]
Awesome!! @Tobotimus Look forward to using it :) 

Also, keeping the 'alert channel' for members, is great as well.. less work for you and users :)

**Comment by Kovaelin** [comment]
@Tobotimus Thank you for your work on this. Would it be possible to make the alert deletion after streams end to be a toggle option? Thanks again.
