### ISSUE TITLE
[streamroles] little bit buggy recently

### ISSUE THREAD

**Issue by theMisteryDE** [Tobotimus/Tobo-Cogs#68]
Lately I recognized that streamroles doesn't work properly anymore. At first I didn't white or blacklist roles, so that everyone on the Server gets a notification. That didn't work properly for a while now, so I whitelisted a role.
Now I have to reload the cog every couple of hours because the Bot seems to forget, that this cog has a duty too fulfill. Sometimes it doesn't give a role and notifies, sometimes it doesn't take the role and the notification away.
With [p]traceback there is no error to find.

**Comment by Tobotimus** [comment]
Should be less buggy now. I've made some updates to accommodate some old breaking changes in discord.py. Give the updates a go :)
