### ISSUE TITLE
[streamroles] alerts not showing game title

### ISSUE THREAD

**Issue by Kovaelin** [Tobotimus/Tobo-Cogs#70]
I'm not sure if this is a bug or intentional, but after an update (first in a long time), I noticed that the alert header went from "user#### updated" to "user#### (ID number) updated". Would it be possible to remove/toggle the ID number to how it was before? Thank you.

**Comment by Tobotimus** [comment]
I'm not sure what you mean, could you post a screenshot? It should look like this:

> **Tobotimus** is now live on Twitch, playing *Tom Clancy's Rainbow Six: Siege*:
> 
> *Playing some T-Hunt*
>
> https://twitch.tv/Tobotimus

The name should be the user's display-name, as it appears above their messages (without any #0000 or ID)

**Comment by Kovaelin** [comment]
My mistake. I should have linked this issue to the general mod functions. However, I noticed a different issue with game titles not being displayed, and only the title (twice):

> Tobotimus is now live on Twitch, playing Playing some T-Hunt:
> 
> Playing some T-Hunt
>
> https://twitch.tv/Tobotimus

**Comment by Tobotimus** [comment]
@Kovaelin that alert doesn't look like it's on the latest version. Can you update and check again?
