### ISSUE TITLE
[Sticky] Feature Request: Only repost when message covered up

### ISSUE THREAD

**Issue by DoctorDinosaur** [Tobotimus/Tobo-Cogs#74]
Add an option so instead of reposting every message, it calculates current line length of chat; and repost when it exceeds the maximum displayed on discord desktop/mobile. Or, slightly less than the maximum, so the message is near the bottom but not constantly reposted.

**Comment by Tobotimus** [comment]
Instead of this, I've implemented #78, which is simply a time-based cooldown. I'm afraid your proposal is just too complex, though thanks for making the feature request regardless :)
