### ISSUE TITLE
[ReactKarma] Option to ignore the bots self react adding/removing karma.

### ISSUE THREAD

**Issue by Dolyfin** [Tobotimus/Tobo-Cogs#81]
I have another cog that auto adds the upvote and downvote emoji to any message in a channel, however this causes the issue that the user always gains 1 karma because the bot counts its own reaction.

**Comment by Tobotimus** [comment]
Thanks for opening this - I've decided to just make ReactKarma ignore reactions from any bot, not just the bot with the cog loaded.
