### ISSUE TITLE
[StreamRoles] Cog is incompatible with tmerc's `streamrole` cog

### ISSUE THREAD

**Issue by Menteroth** [Tobotimus/Tobo-Cogs#82]
Read from here in Tmerc's channel to see the issue I was having and was also fixed when I unloaded your stream cog. I was using his and yours at the same time.

https://ptb.discord.com/channels/240154543684321280/247792146168545291/963105893573095455

**Comment by Tobotimus** [comment]
Yes, the two cogs are probably trying to do similar things, so they are likely to interfere with one another. I would suggest using one cog, or the other, depending on your preference.

I don't plan on adding compatibility with Tmerc's cog.

Thanks!
