### ISSUE TITLE
Dpy2/Red3.5 compatible branch

### ISSUE THREAD

**Issue by aikaterna** [Tobotimus/Tobo-Cogs#85]
Hi Toby, hope things are going well. Do you think you might be able to make a branch to target PRs against, for the future version of Red? Things are getting closer to the date for the switchover and folks still use your cogs fairly frequently.

**Comment by Tobotimus** [comment]
Hey @aikaterna, sounds exciting! I'll give the migration a go :)

**Comment by Tobotimus** [comment]
I've made some changes which add support for dpy 2 and Red 3.5 whilst still supporting previous versions. So the upgrade should be fairly seamless for users, without the need to reference a separate branch.

Thanks!
