### ISSUE TITLE
[Streamroles] No update in roles when streaming status changes

### ISSUE THREAD

**Issue by X-Vaskys** [Tobotimus/Tobo-Cogs#87]
I've noticed that the cog isn't updating roles when people start/stop streaming anymore, unless I manually reload the cog, or use Bobloy (Fox-V3)'s FIFO cog to reload the cog on an interval. I can't provide any form of traceback or error message/code, as the bot/console doesn't seem to be outputting one.

**Comment by Tobotimus** [comment]
Hi @X-Vaskys! Thanks for the bug report.

It seems as though there was an breaking change in Discord.py 2.0 which I hadn't accounted for in StreamRoles. It meant that the cog never received an event to say a user had started or stopped streaming.

I'm just about to update the cog to account for this change, hopefully this will fix the issue.

I'm also adding a new command, `[p]streamrole forceupdate`, which will force the bot to re-inspect all member statuses to see if the streamrole needs to be assigned or removed to any users. This would basically have the same effect as reloading the cog, except it will only update the members in the current Discord server.
