### ISSUE TITLE
Check mod or permissions of the allstrikes commands.

### ISSUE THREAD

**Issue by tintinnabulate** [Tobotimus/Tobo-Cogs#89]
https://github.com/Tobotimus/Tobo-Cogs/blob/8a331807a4bf6c13cd7cd4df169f1f5afbcdc0ac/strikes/strikes.py#L261

Add the decorator ` @checks.mod_or_permissions(kick_members=True)` to the method `allstrikes`.

**Comment by Tobotimus** [comment]
Hi @tintinnabulate, thanks for the bug report! I'll fix this up now

**Comment by tintinnabulate** [comment]
Thanks. 

You will see that I've fixed it in my own fork, and then merged to the master of my own fork.

I did it this way because needed the fix for my discord server asap.

Once you've merged the fix upstream I can delete my fork.

**Comment by Tobotimus** [comment]
Resolved by a3ff70d.

Sorry I didn't see you had committed it to your own fork, I implemented the change myself just now. Thanks again for letting me know!
